Repository xKhana/ayKhana, pull requests merged in 2024-08, with the labels that each got.

#3 config-config-#1-add_spring_basic_config
  .gitignore
  .idea/.gitignore
  Dockerfile
  HELP.md
  compose.yml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/io/github/xkhana/ayKhana/AyKhanaApplication.java
  src/main/java/io/github/xkhana/ayKhana/config/AppConfig.java
  src/main/java/io/github/xkhana/ayKhana/config/SecurityConfig.java
  src/main/java/io/github/xkhana/ayKhana/controller/ProductController.java
  src/main/java/io/github/xkhana/ayKhana/controller/ProductService.java
  src/main/java/io/github/xkhana/ayKhana/exception/BusinessException.java
  src/main/java/io/github/xkhana/ayKhana/model/request/ProductAddition.java
  src/main/java/io/github/xkhana/ayKhana/model/response/ProductRetrieval.java
  src/main/java/io/github/xkhana/ayKhana/security/filter/JwtFilter.java
  src/main/java/io/github/xkhana/ayKhana/security/manager/TokenManager.java
  src/main/java/io/github/xkhana/ayKhana/service/ProductRepository.java
  src/main/java/io/github/xkhana/ayKhana/service/ProductServiceImpl.java
  src/main/java/io/github/xkhana/ayKhana/util/GenericResponse.java
  src/main/resources/application.properties
  src/test/java/io/github/xkhana/ayKhana/AyKhanaApplicationTests.java
Labels: enhancement, good first issue, config, 12h

#4 config-config-#1-add_spring_basic_config
  Dockerfile
  compose.yml
  docs/naming_conventions.md
  src/main/resources/application.properties
Labels: bug, documentation, enhancement, good first issue, config

#5 be-feat-#2-add_entities
  src/main/java/io/github/xkhana/ayKhana/AyKhanaApplication.java
  src/main/java/io/github/xkhana/ayKhana/entity/Address.java
  src/main/java/io/github/xkhana/ayKhana/entity/Category.java
  src/main/java/io/github/xkhana/ayKhana/entity/Customer.java
  src/main/java/io/github/xkhana/ayKhana/entity/Item.java
  src/main/java/io/github/xkhana/ayKhana/entity/Order.java
  src/main/java/io/github/xkhana/ayKhana/entity/OrderItem.java
  src/main/java/io/github/xkhana/ayKhana/entity/Product.java
  src/main/java/io/github/xkhana/ayKhana/entity/ProductImage.java
Labels: 12h, database
